# Generated by Django 3.1.3 on 2022-05-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220522_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='pickup_last',
            new_name='pickup_lat',
        ),
    ]
